import { GateType, PlacedGate } from '../types/quantum';

export interface ConceptQuestion {
  id: string;
  question: string;
  mathPrompt?: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export interface PracticeChallenge {
  id: string;
  title: string;
  category: 'daily' | 'concept' | 'circuit' | 'coding' | 'ai';
  categoryLabel: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  xpReward: number;
  timeEstimate: string;
  description: string;
  badgeReward?: string;
  targetState?: string;
  targetFormula?: string;
  targetProbabilities?: Record<string, number>;
  numQubits?: number;
  allowedGates?: GateType[];
  starterGates?: PlacedGate[];
  hints?: string[];
  scientificExplanation?: string;
  conceptQuestions?: ConceptQuestion[];
  starterCode?: string;
  expectedKeywords?: string[];
  codeTaskDescription?: string;
  expectedTerminalOutput?: string;
  aiPrompt?: string;
  aiInitialResponse?: string;
  aiSuggestedQuestions?: string[];
}

export const PRACTICE_CHALLENGES: PracticeChallenge[] = [
  {
    id: 'daily-bell-state',
    title: 'Build a Bell State |Φ⁺⟩',
    category: 'daily',
    categoryLabel: '🎯 Daily Challenge',
    difficulty: 'Intermediate',
    xpReward: 50,
    timeEstimate: '3 mins',
    description: 'Entangle two qubits into the maximally entangled Bell state |Φ⁺⟩ = (|00⟩ + |11⟩)/√2 using a Hadamard gate and a CNOT gate.',
    badgeReward: 'Entanglement Master',
    targetState: 'bell_state',
    targetFormula: '|Φ⁺⟩ = (|00⟩ + |11⟩) / √2',
    numQubits: 2,
    allowedGates: ['H', 'X', 'Y', 'Z', 'S', 'T', 'CNOT', 'MEASURE'],
    starterGates: [],
    targetProbabilities: {
      '00': 0.5,
      '11': 0.5,
    },
    hints: [
      'Step 1: Put qubit q[0] into an equal superposition using a Hadamard (H) gate.',
      'Step 2: Entangle q[1] with q[0] by placing a CNOT gate with control on q[0] and target on q[1].',
      'Step 3: Measure both qubits (optional in simulator, but validates the measurement register).',
    ],
    scientificExplanation: 'The Bell state |Φ⁺⟩ is generated by applying H on q0: (|0⟩ + |1⟩)/√2 ⊗ |0⟩ = (|00⟩ + |10⟩)/√2. Next, CNOT flips the target qubit q1 if and only if the control qubit q0 is |1⟩, producing (|00⟩ + |11⟩)/√2. This state exhibits non-local correlations that violate the CHSH inequality.',
  },
  {
    id: 'concept-pauli-x',
    title: 'Bit Flip Mastery',
    category: 'concept',
    categoryLabel: '🧠 Concept Drill',
    difficulty: 'Beginner',
    xpReward: 25,
    timeEstimate: '2 mins',
    description: 'Master the action of the Pauli-X gate as a quantum NOT operator, its matrix representation, and its effect on the Bloch sphere.',
    conceptQuestions: [
      {
        id: 'px-q1',
        question: 'What is the action of the Pauli-X gate on the computational basis state |0⟩?',
        options: [
          'It leaves |0⟩ unchanged',
          'It transforms |0⟩ into |1⟩ (bit flip)',
          'It creates an equal superposition (|0⟩ + |1⟩)/√2',
          'It introduces a relative phase of -1',
        ],
        correctIndex: 1,
        explanation: 'Pauli-X acts as the quantum bit-flip operator (analogous to classical NOT): X|0⟩ = |1⟩ and X|1⟩ = |0⟩.',
      },
      {
        id: 'px-q2',
        question: 'What is the matrix representation of the Pauli-X gate in the computational basis {|0⟩, |1⟩}?',
        options: [
          '[[1, 0], [0, 1]] (Identity)',
          '[[1, 0], [0, -1]] (Pauli-Z)',
          '[[0, 1], [1, 0]] (Pauli-X)',
          '[[0, -i], [i, 0]] (Pauli-Y)',
        ],
        correctIndex: 2,
        explanation: 'The matrix [[0, 1], [1, 0]] swaps the coefficients of |0⟩ and |1⟩: [[0, 1], [1, 0]] * [1, 0]^T = [0, 1]^T.',
      },
      {
        id: 'px-q3',
        question: 'Geometrically on the Bloch sphere, applying a Pauli-X gate corresponds to what transformation?',
        options: [
          'A 90° rotation about the Z-axis',
          'A 180° (π radians) rotation about the X-axis',
          'A reflection across the XY equatorial plane',
          'A contraction of the state vector toward the origin',
        ],
        correctIndex: 1,
        explanation: 'Pauli gates correspond to 180° (π rad) rotations about their respective Cartesian axes on the Bloch sphere. A π rotation about X flips the North Pole (|0⟩) to the South Pole (|1⟩).',
      },
    ],
    scientificExplanation: 'The Pauli-X operator is a self-inverse unitary (X² = I) Hermitian matrix representing spin-1/2 observables along the x-axis. It exchanges the computational basis states |0⟩ and |1⟩ while keeping the equatorial state |+⟩ invariant up to a global phase.',
  },
  {
    id: 'circuit-superposition-3q',
    title: 'GHZ State Synthesis',
    category: 'circuit',
    categoryLabel: '⚛️ Circuit Practice',
    difficulty: 'Advanced',
    xpReward: 45,
    timeEstimate: '4 mins',
    description: 'Construct the Greenberger-Horne-Zeilinger (GHZ) 3-qubit state: (|000⟩ + |111⟩)/√2 using a cascade of CNOT gates.',
    badgeReward: 'GHZ Pioneer',
    targetState: 'ghz_state',
    targetFormula: '|GHZ⟩ = (|000⟩ + |111⟩) / √2',
    numQubits: 3,
    allowedGates: ['H', 'X', 'Y', 'Z', 'S', 'T', 'CNOT', 'MEASURE'],
    starterGates: [],
    targetProbabilities: {
      '000': 0.5,
      '111': 0.5,
    },
    hints: [
      'Step 1: Apply a Hadamard gate to qubit q[0] to create (|0⟩ + |1⟩)/√2.',
      'Step 2: Add a CNOT gate with control on q[0] and target on q[1]. Now q0 and q1 are in a Bell state.',
      'Step 3: Add a second CNOT gate with control on q[1] and target on q[2] to entangle the third qubit.',
    ],
    scientificExplanation: 'The GHZ state is an extreme demonstration of genuine tripartite quantum entanglement. Measuring any single qubit immediately projects all three qubits into either |000⟩ or |111⟩ with equal 50% probability, leaving no intermediate states.',
  },
  {
    id: 'circuit-superposition-single',
    title: 'Superposition Constructor',
    category: 'circuit',
    categoryLabel: '⚛️ Circuit Practice',
    difficulty: 'Beginner',
    xpReward: 30,
    timeEstimate: '2 mins',
    description: 'Create an equal superposition state |+⟩ = (|0⟩ + |1⟩)/√2 on a single qubit, resulting in a 50/50 measurement distribution.',
    targetFormula: '|+⟩ = (|0⟩ + |1⟩) / √2',
    numQubits: 1,
    allowedGates: ['H', 'X', 'Y', 'Z', 'S', 'T', 'MEASURE'],
    starterGates: [],
    targetProbabilities: {
      '0': 0.5,
      '1': 0.5,
    },
    hints: [
      'A single Hadamard (H) gate transforms the initial ground state |0⟩ into the superposition state |+⟩.',
      'Verify the probability chart displays 50% probability on state 0 and 50% on state 1.',
    ],
    scientificExplanation: 'The Hadamard operator maps orthogonal basis states onto the equator of the Bloch sphere: H|0⟩ = (|0⟩ + |1⟩)/√2 = |+⟩, with equal probability P(0) = |1/√2|² = 0.5 and P(1) = 0.5.',
  },
  {
    id: 'coding-qiskit-rng',
    title: 'True Quantum RNG in Qiskit',
    category: 'coding',
    categoryLabel: '💻 Coding Practice',
    difficulty: 'Beginner',
    xpReward: 35,
    timeEstimate: '4 mins',
    description: 'Write an authentic Qiskit Python program that initializes a qubit in superposition, measures it, and returns genuinely random quantum bits.',
    codeTaskDescription: 'Initialize a 1-qubit QuantumCircuit with 1 classical bit, apply a Hadamard gate to qubit 0, and measure qubit 0 onto classical bit 0.',
    starterCode: `# True Quantum Random Number Generator in Qiskit
from qiskit import QuantumCircuit, Aer, execute

# 1. Create a quantum circuit with 1 qubit and 1 classical bit
qc = QuantumCircuit(1, 1)

# TODO: Apply Hadamard gate to qubit 0 to create true quantum randomness
# Hint: qc.h(0)

# TODO: Measure qubit 0 into classical bit 0
# Hint: qc.measure(0, 0)

# 2. Simulate circuit using QasmSimulator
simulator = Aer.get_backend('qasm_simulator')
job = execute(qc, simulator, shots=1024)
result = job.result()
counts = result.get_counts(qc)

print("Quantum RNG Output Counts:", counts)
`,
    expectedKeywords: ['qc.h(0)', 'qc.measure(0, 0)'],
    expectedTerminalOutput: `Compiling quantum circuit...
Simulating on Aer.qasm_simulator with 1024 shots...
Quantum RNG Output Counts: {'0': 512, '1': 512}
Entropy: 1.000 bits (True Non-Deterministic Quantum Randomness)
Status: Verification PASSED!`,
    hints: [
      'Write `qc.h(0)` to put qubit 0 into superposition.',
      'Write `qc.measure(0, 0)` to perform projective measurement into classical bit 0.',
    ],
    scientificExplanation: 'Unlike pseudo-random number generators (PRNG) based on deterministic algorithms, a quantum RNG leverages the inherent non-determinism of Born-rule wavefunction collapse, yielding provably unpredictable numbers.',
  },
  {
    id: 'ai-phase-estimation',
    title: 'Quantum Phase Estimation',
    category: 'ai',
    categoryLabel: '🤖 AI Challenge',
    difficulty: 'Advanced',
    xpReward: 50,
    timeEstimate: '5 mins',
    description: 'Engage with QBIT AI to explore the eigenvalue phase problem U|ψ⟩ = e^{2πiθ}|ψ⟩ and understand how inverse QFT reads out the phase θ.',
    aiPrompt: 'Explain how Quantum Phase Estimation extracts the phase θ of an eigenvalue e^{2πiθ} using controlled-U operations and the inverse Quantum Fourier Transform (QFT†).',
    aiInitialResponse: `Welcome to the Quantum Phase Estimation (QPE) challenge! ⚛️

In QPE, we have a unitary operator U with an eigenvector |ψ⟩ such that:
U|ψ⟩ = e^(2πiθ)|ψ⟩

Our goal is to determine the unknown phase parameter θ ∈ [0, 1).

Here is the algorithmic sequence:
1. Prepare an evaluation register of t qubits initialized to |0⟩^⊗t and state register in |ψ⟩.
2. Apply Hadamard gates across the entire evaluation register.
3. Apply successive controlled-U^(2^j) operations.
4. Apply the Inverse Quantum Fourier Transform (QFT†) to the evaluation register.
5. Measure the evaluation register to retrieve an n-bit binary estimate of θ!

Try asking me:
• "How does phase kickback encode θ into the evaluation register?"
• "Why is QFT† required at the end of QPE?"
• "How is QPE used in Shor's factoring algorithm?"`,
    aiSuggestedQuestions: [
      'How does phase kickback encode θ into the evaluation register?',
      'Why is QFT† required at the end of QPE?',
      'How is QPE used in Shor\'s factoring algorithm?',
    ],
    scientificExplanation: 'Quantum Phase Estimation is a cornerstone quantum subroutine powering both Shor\'s factoring algorithm and quantum chemistry ground-state energy calculations (VQE and phase estimation).',
  },
];
